
-- Criado por Ricardo Pedrotti em 26/04/2018
-- Atualizado em: 12/06/2018

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BEESPORTS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS BEESPORTS ;

-- -----------------------------------------------------
-- Schema BEESPORTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS BEESPORTS DEFAULT CHARACTER SET utf8 ;
USE BEESPORTS ;

-- -----------------------------------------------------
-- Table BEESPORTS.TB_PAIS
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_PAIS ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_PAIS (
  CD_PAIS INT NOT NULL AUTO_INCREMENT,
  NM_PAIS VARCHAR(45) NULL,
  PRIMARY KEY (CD_PAIS))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table BEESPORTS.TB_ESTADO
-- -----------------------------------------------------

DROP TABLE IF EXISTS BEESPORTS.TB_ESTADO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_ESTADO (
  CD_ESTADO INT NOT NULL AUTO_INCREMENT,
  SG_ESTADO VARCHAR (2) NULL,
  NM_ESTADO VARCHAR(45) NULL,
  CD_PAIS INT NOT NULL,
  PRIMARY KEY (CD_ESTADO),
  CONSTRAINT FK_ESTADO_PAIS
    FOREIGN KEY (CD_PAIS)
    REFERENCES BEESPORTS.TB_PAIS (CD_PAIS)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;

CREATE INDEX CD_PAIS_idx ON BEESPORTS.TB_ESTADO (CD_PAIS ASC);

-- -----------------------------------------------------
-- Table BEESPORTS.TB_CIDADE
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_CIDADE ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_CIDADE (
  CD_CIDADE INT NOT NULL AUTO_INCREMENT,
  NM_CIDADE VARCHAR(45) NULL,
  CD_ESTADO INT NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  PRIMARY KEY (CD_CIDADE),
  CONSTRAINT FK_CIDADE_ESTADO
    FOREIGN KEY (CD_ESTADO)
    REFERENCES BEESPORTS.TB_ESTADO (CD_ESTADO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_ESTADO_idx ON BEESPORTS.TB_CIDADE (CD_ESTADO ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_ENDERECO
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_ENDERECO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_ENDERECO (
  CD_ENDERECO INT NOT NULL AUTO_INCREMENT,
  DS_ENDERECO VARCHAR(100) NULL,
  DS_ENDERECO2 VARCHAR(50) NULL,
  CD_CEP VARCHAR(20) NULL,
  NM_BAIRRO VARCHAR(50) NULL,
  CD_CIDADE INT NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  PRIMARY KEY (CD_ENDERECO),
  CONSTRAINT FK_ENDERECO_CIDADE
    FOREIGN KEY (CD_CIDADE)
    REFERENCES BEESPORTS.TB_CIDADE (CD_CIDADE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_CIDADE_idx ON BEESPORTS.TB_ENDERECO (CD_CIDADE ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_RESPONSAVEL
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_RESPONSAVEL ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_RESPONSAVEL (
  CD_RESPONSAVEL INT NOT NULL AUTO_INCREMENT,
  NM_RESPONSAVEL VARCHAR(45) NULL,
  DS_SEXO VARCHAR(1) NULL,
  NM_EMAIL VARCHAR(100) NULL,
  NM_PRIMEIRO_NOME VARCHAR(45) NULL,
  NM_ULTIMO_NOME VARCHAR(45) NULL,
  DT_NASCIMENTO DATE NULL,
  CD_RG VARCHAR(20) NULL,
  CD_CPF VARCHAR(20) NULL,
  CD_ENDERECO INT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  NU_TELEFONE_RES VARCHAR(20) NULL,
  NU_TELEFONE_CEL VARCHAR(20) NULL,
  PRIMARY KEY (CD_RESPONSAVEL),
  CONSTRAINT FK_RESPONSAVEL_ENDERECO
    FOREIGN KEY (CD_ENDERECO)
    REFERENCES BEESPORTS.TB_ENDERECO (CD_ENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX cd_atleta_UNIQUE ON BEESPORTS.TB_RESPONSAVEL (CD_RESPONSAVEL ASC);

CREATE INDEX CD_ENDERECO_idx ON BEESPORTS.TB_RESPONSAVEL (CD_ENDERECO ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_ATLETA
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_ATLETA ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_ATLETA (
  CD_ATLETA INT NOT NULL AUTO_INCREMENT,
  NM_ATLETA VARCHAR(45) NULL,
  DS_SEXO VARCHAR(1) NULL,
  NM_EMAIL VARCHAR(100) NULL,
  NM_PRIMEIRO_NOME VARCHAR(45) NULL,
  NM_ULTIMO_NOME VARCHAR(45) NULL,
  DT_NASCIMENTO DATE NULL,
  CD_RG_ATLETA VARCHAR(20) NULL,
  CD_CPF_ATLETA VARCHAR(20) NULL,
  CD_ENDERECO INT NULL,
  CD_RESPONSAVEL INT NULL,
  FOTO_ATLETA LONGBLOB NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  NU_TELEFONE_RES VARCHAR(20) NULL,
  NU_TELEFONE_CEL VARCHAR(20) NULL,
  PRIMARY KEY (CD_ATLETA),
  CONSTRAINT FK_ATLETA_ENDERECO
    FOREIGN KEY (CD_ENDERECO)
    REFERENCES BEESPORTS.TB_ENDERECO (CD_ENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_ATLETA_RESPONSAVEL
    FOREIGN KEY (CD_RESPONSAVEL)
    REFERENCES BEESPORTS.TB_RESPONSAVEL (CD_RESPONSAVEL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_ENDERECO_idx ON BEESPORTS.TB_ATLETA (CD_ENDERECO ASC);

CREATE INDEX CD_RESPONSAVEL_idx ON BEESPORTS.TB_ATLETA (CD_RESPONSAVEL ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_INSTITUICAO
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_INSTITUICAO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_INSTITUICAO (
  CD_INSTITUICAO INT NOT NULL AUTO_INCREMENT,
  NM_INSTITUICAO VARCHAR(100) NULL,
  NM_FANTASIA_INSTITUICAO VARCHAR(50) NULL,
  CD_CNPJ VARCHAR(25) NULL,
  CD_ENDERECO INT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  PRIMARY KEY (CD_INSTITUICAO),
  CONSTRAINT FK_INSTITUICAO_ENDERECO
    FOREIGN KEY (CD_ENDERECO)
    REFERENCES BEESPORTS.TB_ENDERECO (CD_ENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_ENDERECO_idx ON BEESPORTS.TB_INSTITUICAO (CD_ENDERECO ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_TREINADOR
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_TREINADOR ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_TREINADOR (
  CD_TREINADOR INT NOT NULL AUTO_INCREMENT,
  NM_TREINADOR VARCHAR(100) NULL,
  DS_SEXO VARCHAR(1) NULL,
  NM_EMAIL VARCHAR(50) NULL,
  NM_PRIMEIRO_NOME VARCHAR(45) NULL,
  NM_ULTIMO_NOME VARCHAR(45) NULL,
  DT_NASCIMENTO DATE NULL,
  CD_RG VARCHAR(20) NULL,
  CD_CPF VARCHAR(20) NULL,
  CD_ENDERECO INT NULL,
  FOTO LONGBLOB NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  CD_INSTITUICAO INT NULL,
  NU_TELEFONE_RES VARCHAR(20) NULL,
  NU_TELEFONE_CEL VARCHAR(20) NULL,
  PRIMARY KEY (CD_TREINADOR),
  CONSTRAINT FK_TREINADOR_ENDERECO
    FOREIGN KEY (CD_ENDERECO)
    REFERENCES BEESPORTS.TB_ENDERECO (CD_ENDERECO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TREINADOR_INSTITUICAO
    FOREIGN KEY (CD_INSTITUICAO)
    REFERENCES BEESPORTS.TB_INSTITUICAO (CD_INSTITUICAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_ENDERECO_idx ON BEESPORTS.TB_TREINADOR (CD_ENDERECO ASC);

CREATE INDEX CD_INSTITUICAO_idx ON BEESPORTS.TB_TREINADOR (CD_INSTITUICAO ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_ESPORTES
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_ESPORTES ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_ESPORTES (
  CD_ESPORTE INT NOT NULL AUTO_INCREMENT,
  NM_ESPORTE VARCHAR(45) NULL,
  DS_ESPORTE VARCHAR(45) NULL,
  PRIMARY KEY (CD_ESPORTE))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table BEESPORTS.TB_DISPOSITIVO
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_DISPOSITIVO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_DISPOSITIVO (
  CD_SERIAL_DISPOSITIVO VARCHAR(20) NOT NULL,
  DS_DISPOSITIVO VARCHAR(45) NULL,
  CD_INSTITUICAO INT NOT NULL,
  CD_TREINADOR INT NOT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  DH_ULTIMA_ATU TIMESTAMP NOT NULL,
  PRIMARY KEY (CD_SERIAL_DISPOSITIVO),
  CONSTRAINT FK_DISPOSITIVO_INSTITUICAO
    FOREIGN KEY (CD_INSTITUICAO)
    REFERENCES BEESPORTS.TB_INSTITUICAO (CD_INSTITUICAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_DISPOSITIVO_TREINADOR
    FOREIGN KEY (CD_TREINADOR)
    REFERENCES BEESPORTS.TB_TREINADOR (CD_TREINADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_INSTITUICAO_FK_idx ON BEESPORTS.TB_DISPOSITIVO (CD_INSTITUICAO ASC);

CREATE INDEX CD_TREINADOR_FK_idx ON BEESPORTS.TB_DISPOSITIVO (CD_TREINADOR ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_TREINO
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_TREINO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_TREINO (
  CD_TREINO INT NOT NULL AUTO_INCREMENT,
  DS_TREINO VARCHAR(45) NULL,
  CD_INSTITUICAO INT NOT NULL,
  CD_TREINADOR INT NOT NULL,
  CD_ATLETA INT NOT NULL,
  CD_SERIAL_DISPOSITIVO VARCHAR(20) NOT NULL,
  CD_ESPORTE INT NULL,
  DH_INICIO_TREINO DATETIME NULL,
  DH_FIM_TREINO DATETIME NULL,
  PRIMARY KEY (CD_TREINO),
  CONSTRAINT FK_TREINO_INSTITUICAO
    FOREIGN KEY (CD_INSTITUICAO)
    REFERENCES BEESPORTS.TB_INSTITUICAO (CD_INSTITUICAO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TREINO_TREINADOR
    FOREIGN KEY (CD_TREINADOR)
    REFERENCES BEESPORTS.TB_TREINADOR (CD_TREINADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TREINO_ATLETA
    FOREIGN KEY (CD_ATLETA)
    REFERENCES BEESPORTS.TB_ATLETA (CD_ATLETA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TREINO_ESPORTES
    FOREIGN KEY (CD_ESPORTE)
    REFERENCES BEESPORTS.TB_ESPORTES (CD_ESPORTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_TREINO_DISPOSITIVO
    FOREIGN KEY (CD_SERIAL_DISPOSITIVO)
    REFERENCES BEESPORTS.TB_DISPOSITIVO (CD_SERIAL_DISPOSITIVO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_INSTITUICAO_idx ON BEESPORTS.TB_TREINO (CD_INSTITUICAO ASC);

CREATE INDEX CD_TREINADOR_idx ON BEESPORTS.TB_TREINO (CD_TREINADOR ASC);

CREATE INDEX CD_ATLETA_idx ON BEESPORTS.TB_TREINO (CD_ATLETA ASC);

CREATE INDEX CD_ESPORTE_idx ON BEESPORTS.TB_TREINO (CD_ESPORTE ASC);

CREATE INDEX CD_SERIAL_DISPOSITIVO_idx ON BEESPORTS.TB_TREINO (CD_SERIAL_DISPOSITIVO ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_LOGIN
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_LOGIN ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_LOGIN (
  LOGIN VARCHAR(50) NOT NULL,
  PASSWD VARCHAR(50) NOT NULL,
  CD_ATLETA INT NULL,
  CD_TREINADOR INT NULL,
  CD_RESPONSAVEL INT NULL,
  DH_ULTIMO_LOGIN TIMESTAMP NOT NULL,
  PRIMARY KEY (LOGIN),
  CONSTRAINT FK_LOGIN_ATLETA
    FOREIGN KEY (CD_ATLETA)
    REFERENCES BEESPORTS.TB_ATLETA (CD_ATLETA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_LOGIN_TREINADOR
    FOREIGN KEY (CD_TREINADOR)
    REFERENCES BEESPORTS.TB_TREINADOR (CD_TREINADOR)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_LOGIN_RESPONSAVEL
    FOREIGN KEY (CD_RESPONSAVEL)
    REFERENCES BEESPORTS.TB_RESPONSAVEL (CD_RESPONSAVEL)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_ATLETA_idx ON BEESPORTS.TB_LOGIN (CD_ATLETA ASC);

CREATE INDEX CD_TREINADOR_idx ON BEESPORTS.TB_LOGIN (CD_TREINADOR ASC);

CREATE INDEX CD_RESPONSAVEL_idx ON BEESPORTS.TB_LOGIN (CD_RESPONSAVEL ASC);


-- -----------------------------------------------------
-- Table BEESPORTS.TB_STREAM_TREINO
-- -----------------------------------------------------
DROP TABLE IF EXISTS BEESPORTS.TB_STREAM_TREINO ;

CREATE TABLE IF NOT EXISTS BEESPORTS.TB_STREAM_TREINO (
  CD_SERIAL_DISPOSITIVO VARCHAR(20) NOT NULL,
  DS_JSON VARCHAR(255) NULL,
  DADO1 INT NULL,
  DADO2 VARCHAR(45) NULL,
  DADO3 TINYINT NULL,
  DH_CRIACAO TIMESTAMP NOT NULL,
  CONSTRAINT FK_STREAM_DISPOSITIVO
    FOREIGN KEY (CD_SERIAL_DISPOSITIVO)
    REFERENCES BEESPORTS.TB_DISPOSITIVO (CD_SERIAL_DISPOSITIVO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX CD_SERIAL_DISPOSITIVO_idx ON BEESPORTS.TB_STREAM_TREINO (CD_SERIAL_DISPOSITIVO ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
